[bell]
animation = "Ease"
duration = 0

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi|~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchConfirm"
key = "Return"
mode = "Search|Vi"

[[keyboard.bindings]]
action = "SearchCancel"
key = "Escape"
mode = "Search"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "Return"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "Return"
mode = "Search|~Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[selection]
save_to_clipboard = false

[window]
decorations = "buttonless"
startup_mode = "Fullscreen"
title = "Alacritty"
